name: example
publish_to: none
version: 0.0.1
homepage: https://cubealgos.xyz
repository: https://github.com/cubealgos/web3dart_async

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  web3dart_async:
    path: ../
  http: ^1.1.0
  wallet: ^0.0.17
  web_socket_channel: ^2.2.0

dev_dependencies:
  test: ^1.22.0
  coverage: ^1.1.0
  lints: ^2.0.0
